// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClKSRMgjBvrIpu115yM0BdMRIMJZ3mJTg',
    appId: '1:889287193763:web:24941aff02421be407bb16',
    messagingSenderId: '889287193763',
    projectId: 'blab-d3655',
    authDomain: 'blab-d3655.firebaseapp.com',
    storageBucket: 'blab-d3655.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS8xxofXILj1VE6f4oduadUhbRuwUoHIM',
    appId: '1:889287193763:android:92a48b881b748a7f07bb16',
    messagingSenderId: '889287193763',
    projectId: 'blab-d3655',
    storageBucket: 'blab-d3655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzjggm0r1lsMVHk0Vo7k4XlxI56ejrU8s',
    appId: '1:889287193763:ios:d56f58b8fc3cd70d07bb16',
    messagingSenderId: '889287193763',
    projectId: 'blab-d3655',
    storageBucket: 'blab-d3655.appspot.com',
    iosClientId: '889287193763-u80bkhcdabhrs4iijsf01pevld4fh5bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.blab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzjggm0r1lsMVHk0Vo7k4XlxI56ejrU8s',
    appId: '1:889287193763:ios:c136baf49c4f8e2b07bb16',
    messagingSenderId: '889287193763',
    projectId: 'blab-d3655',
    storageBucket: 'blab-d3655.appspot.com',
    iosClientId: '889287193763-aovtioa1h6ka4rlmglbijpelug44jome.apps.googleusercontent.com',
    iosBundleId: 'com.example.blab.RunnerTests',
  );
}
